# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNSKLinkedMapModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNSKLinkedMapModule

  pod 'react-native-image-crop-tools', :path => '../node_modules/react-native-image-crop-tools'

end
